server:
  port: 8081

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: taskflow
    password: taskflow
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    locale: en_US
    locale-resolver: fixed