server:
  port: 8081

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: taskflow
    password: taskflow
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    locale: en_US
    locale-resolver: fixed
jwt:
   secret: "O21zhID3aNOimTj4tL0lY006e7ppD3K0MiwYOhPbN7y7YUtZ1k5LDytv8iOJTyBv"
   expiration-ms: 86400000  # 24 horas
